Support multiple keyspaces
BlueBrain/nexus-sourcing pull request #16
Opened 2018-05-27 17:02 UTC by hygt

Implements #15

2018-05-28 07:19 UTC, bogdanromanx requested changes
Please rename `PersistentId` to `PersistenceId` and move it to the `akka` module; as far as I can tell, the in memory implementation needs not have a fixed id type, it can be a type parameter specified during construction.

I would also recommend renaming the `keyspace` field to something like `qualifier` to avoid cassandra specificity.

2018-05-28 20:07 UTC, bogdanromanx submitted a review, later dismissed

2018-05-29 08:49 UTC, umbreak commented on modules/akka/src/main/scala/ch/epfl/bluebrain/nexus/sourcing/akka/ShardingAggregate.scala
> +)(implicit as: ActorSystem, ec: ExecutionContext, mt: Materializer, tm: Timeout)
If you pass the `ActorSystem` here, why do you need the `ExecutionContext ` and the `Materializer`? Both can be derived form the `ActorSystem`, right?

2018-05-31 08:37 UTC, umbreak approved these changes

2018-05-31 08:41 UTC, merged